# Generated by Django 3.1.1 on 2020-09-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis_usuarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfil_usuaria',
            table='usuaria',
        ),
    ]
